services:
  nginx:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    container_name: webserver
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    networks:
      - internal_network
    env_file:
      - server_config.env
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}

  auto-ssl-proxy:
    image: docker.io/valian/docker-nginx-auto-ssl
    container_name: auto-ssl-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: $(ALLOWED_DOMAINS)
      SITES: $(SITES)
      FORCE_HTTPS: 'true'
    depends_on:
      - nginx
    networks: 
      - internal_network
    env_file:
      - server_config.env

volumes:
  ssl_data:

networks:
  internal_network:
    driver: bridge
